import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { serverSideHelpers } from "~/lib/serverSideHelpers";

import { api } from "~/utils/api";

import PartnershipCard from "~/components/partnershipCard";

const Home: NextPage = () => {
  const { data, isLoading, fetchNextPage } =
    api.partnership.getPartnerships.useInfiniteQuery(
      { limit: 10 },
      { getNextPageParam: (lastPage) => lastPage.nextCursor }
    );

  const partnerships = data?.pages.flatMap((page) => page.partnerships) ?? [];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-sky-900 to-sky-950 pt-6">
        <div className="2xl:container">
          <h2 className="my-8 self-start text-2xl text-white">Partnerships</h2>

          <div className="mb-12 grid grid-cols-1 justify-items-center gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {partnerships.map((partnership) => (
              <PartnershipCard key={partnership.id} partnership={partnership} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async ({
  req,
  res,
}: GetServerSidePropsContext) => {
  const helpers = serverSideHelpers({ req, res });
  await helpers.partnership.getPartnerships.prefetchInfinite({ limit: 10 });

  return {
    props: {
      trpcState: helpers.dehydrate(),
    },
  };
};
