import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { serverSideHelpers } from "utils/serverSideHelpers";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading, fetchNextPage } =
    api.partnership.getPartnerships.useInfiniteQuery(
      { limit: 10 },
      { getNextPageParam: (lastPage) => lastPage.nextCursor }
    );
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          Partnerships Page
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async ({
  req,
  res,
}: GetServerSidePropsContext) => {
  const helpers = serverSideHelpers({ req, res });
  await helpers.partnership.getPartnerships.prefetchInfinite({ limit: 10 });

  return {
    props: {
      trpcState: helpers.dehydrate(),
    },
  };
};
